codecov:
  branch: develop
coverage:
  status:
    project:
      full-service:
        target: auto
        threshold: 0%
        paths:
          - "full-service/"
      mirror:
        target: auto
        threshold: 0%
        paths:
          - "mirror/"
      validator:
        target: auto
        threshold: 0%
        paths:
          - "validator/"
