# Copyright (c) 2018-2022 The MobileCoin Foundation
nameOverride: ""
fullnameOverride: ""

imagePullSecrets:
- name: docker-credentials

image:
  org: mobilecoin

## config: is optional. The built containers are batteries included and have the appropriate chainId, peers and txSourceURLs defined by default. config is provided here so you can override if needed.

## Example args for testnet - note the .test chart and container image include these values.
# config:
#   chainId: test
#   peers:
#   - mc://node1.test.mobilecoin.com/
#   - mc://node2.test.mobilecoin.com/
#   txSourceURLs:
#   - https://s3-us-west-1.amazonaws.com/mobilecoin.chain/node1.test.mobilecoin.com/
#   - https://s3-us-west-1.amazonaws.com/mobilecoin.chain/node2.test.mobilecoin.com/
#   ledgerDbURL: https://mcdeveu1ledger.blob.core.windows.net/test/data.mdb

## Example args for mainnet - note the .main chart and container image includes these values. (prod is correct for the urls)
# config:
#   chainId: main
#   peers:
#   - mc://node1.prod.mobilecoin.com/
#   - mc://node2.prod.mobilecoin.com/
#   txSourceURLs:
#   - https://s3-us-west-1.amazonaws.com/mobilecoin.chain/node1.prod.mobilecoin.com/
#   - https://s3-us-west-1.amazonaws.com/mobilecoin.chain/node2.prod.mobilecoin.com/
#   ledgerDbURL: https://mcdeveu1ledger.blob.core.windows.net/main/data.mdb

config:
  chainId: ""
  txSourceURLs: []
  peers: []

fullService:
  replicaCount: 1
  image:
    org: ''
    name: full-service
    tag: ''
  podAnnotations:
    fluentbit.io/include: 'true'
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  persistence:
    enabled: true
    spec:
      storageClassName: fast
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 128Gi
  configMap:
    name: full-service
    data: {}
  secret:
    name: full-service
    stringData: {}

backupsSidecar:
  enabled: false
  image:
    org: ''
    name: infra-replication-sidecar
    tag: v0.0.1
  # Create backups-sidecar secret or set external 'false'
  secret:
    external: true
    name: backups-sidecar
    data:
      ENCRYPT_KEY: <file encryption passphrase>
      AZURE_STORAGE_ACCOUNT: <azure storage account name>
      AZURE_STORAGE_KEY: <azure storage account access key>
