// Copyright (c) 2018-2023 MobileCoin, Inc.

//! Ledger Validator Node gRPC API.

use mc_util_uri::{Uri, UriScheme};

mod autogenerated_code {
    pub use mc_consensus_api::consensus_common;
    pub use mc_fog_report_api::fog_report::*;

    pub mod report {
        pub use mc_fog_report_api::fog_report::*;
    }

    pub use mc_api::{blockchain, external};

    pub mod validator_api {
        include!(concat!(
            env!("OUT_DIR"),
            "/protos-auto-gen/validator_api.rs"
        ));
    }
}

pub use autogenerated_code::{validator_api::*, *};

pub type ValidatorUri = Uri<ValidatorScheme>;

/// Validator  Uri Scheme
#[derive(Debug, Hash, Ord, PartialOrd, Eq, PartialEq, Clone)]
pub struct ValidatorScheme {}
impl UriScheme for ValidatorScheme {
    /// The part before the '://' of a URL.
    const SCHEME_SECURE: &'static str = "validator";
    const SCHEME_INSECURE: &'static str = "insecure-validator";

    /// Default port numbers
    const DEFAULT_SECURE_PORT: u16 = 5553;
    const DEFAULT_INSECURE_PORT: u16 = 5554;
}
