pub const DEFAULT_FIRST_BLOCK_INDEX: u64 = 0;
pub const ROOT_ENTROPY_KEY_DERIVATION_VERSION: u8 = 1;
pub const MNEMONIC_KEY_DERIVATION_VERSION: u8 = 2;
pub const DEFAULT_CHANGE_SUBADDRESS_INDEX: u64 = 1;
pub const DEFAULT_NEXT_SUBADDRESS_INDEX: u64 = 2;
pub const DEFAULT_SUBADDRESS_INDEX: u64 = 0;
