# Copyright (c) 2018-2023 The MobileCoin Foundation
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "fullServiceMirror.fullname" . }}-full-service
  labels:
    {{- include "fullServiceMirror.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.fullService.replicaCount }}
  selector:
    matchLabels:
      app: full-service
      {{- include "fullServiceMirror.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "fullServiceMirror.fullname" . }}-full-service
  template:
    metadata:
      annotations:
        {{- toYaml .Values.fullService.podAnnotations | nindent 8 }}
      labels:
        app: full-service
        {{- include "fullServiceMirror.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 2000
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
      - name: full-service
        securityContext:
          capabilities:
            drop:
            - all
          readOnlyRootFilesystem: true
        image: {{ include "fullServiceMirror.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ include "fullServiceMirror.fullname" . }}-full-service
        args:
        ports:
        - name: full-service
          containerPort: 9090
          protocol: TCP
        startupProbe:
          httpGet:
            path: /health
            port: full-service
          failureThreshold: 300
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: full-service
          failureThreshold: 2
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: full-service
          initialDelaySeconds: 5
          failureThreshold: 10
          periodSeconds: 5
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          {{- toYaml .Values.fullService.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.fullService.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.fullService.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.fullService.tolerations | nindent 8 }}
      {{- if eq .Values.fullService.persistence.enabled false }}
      volumes:
      - name: data
        emptyDir: {}
      {{- end }}
  {{- if .Values.fullService.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      {{- toYaml .Values.fullService.persistence.spec | nindent 6 }}
  {{- end }}
