{{- if .Values.fullService.secret.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullServiceMirror.fullService.secret.name" . }}
  labels:
    {{- include "fullServiceMirror.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.fullService.secret.data | nindent 2 }}
{{- end }}
