{{- if .Values.private.secret.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullServiceMirror.private.secret.name" . }}
  labels:
    {{- include "fullServiceMirror.labels" . | nindent 4 }}
type: Opaque
data:
  mirror-private.pem: {{ index .Values "private" "secret" "data" "mirror-private.pem" | b64enc }}
{{- end }}
