# Copyright (c) 2018-2023 The MobileCoin Foundation
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullServiceMirror.fullname" . }}-validator
  labels:
    {{- include "fullServiceMirror.labels" . | nindent 4 }}
    app: validator
data:
{{- if .Values.config.chainId }}
  MC_CHAIN_ID: {{ .Values.config.chainId | quote }}
{{- end }}
{{- if .Values.config.txSourceURLs }}
  MC_TX_SOURCE_URL: {{ join "," .Values.config.txSourceURLs | quote }}
{{- end }}
{{- if .Values.config.peers }}
  MC_PEER: {{ join "," .Values.config.peers | quote }}
{{- end }}
{{- if .Values.config.ledgerDbURL }}
  MC_LEDGER_DB_URL: {{ .Values.config.ledgerDbURL | quote }}
{{- end }}
