# Copyright (c) 2018-2022 The MobileCoin Foundation
{{ if eq .Values.backupsSidecar.secret.external false }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "fullService.backupsSidecar.secret.name" . }}
  labels:
    {{- include "fullService.labels" . | nindent 4 }}
data:
  ENCRYPT_KEY: {{ .Values.backupsSidecar.secret.data.ENCRYPT_KEY | b64enc }}
  AZURE_STORAGE_ACCOUNT: {{ .Values.backupsSidecar.secret.data.AZURE_STORAGE_ACCOUNT | b64enc }}
  AZURE_STORAGE_KEY: {{ .Values.backupsSidecar.secret.data.AZURE_STORAGE_KEY | b64enc }}
{{- end }}
