# Copyright (c) 2018-2022 The MobileCoin Foundation
{{ if eq .Values.fullService.configMap.external false }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullService.fullname" . }}
  labels:
    {{- include "fullService.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.fullService.configMap.data | nindent 2}}
{{- end }}
