apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullService.fullname" . }}
  labels:
    {{- include "fullService.labels" . | nindent 4 }}
stringData:
{{- if .Values.fullService.secret.data }}
  {{- toYaml .Values.fullService.secret.data | nindent 2 }}
{{- end }}
