// Copyright (c) 2018-2021 MobileCoin Inc.

mod autogenerated_code {
    // Include the auto-generated code.
    include!(concat!(env!("OUT_DIR"), "/protos-auto-gen/mod.rs"));
}

pub use autogenerated_code::{wallet_service_mirror_api::*, *};

pub mod uri;
