// Copyright (c) 2018-2021 MobileCoin Inc.

// workaround for #![allow(box_pointers)] in protobuf generated files.
#![allow(renamed_and_removed_lints)]

mod autogenerated_code {
    // Expose proto data types from included third-party/external proto files.
    pub use mc_api::{blockchain, external};
    pub use protobuf::well_known_types::Empty;

    // Needed due to how to the auto-generated code references the Empty message.
    pub mod empty {
        pub use protobuf::well_known_types::Empty;
    }

    // Include the auto-generated code.
    include!(concat!(env!("OUT_DIR"), "/protos-auto-gen/mod.rs"));
}

pub use autogenerated_code::{wallet_service_mirror_api::*, *};

pub mod uri;
