name: docker-hub

env:
  DOCKERHUB_REPO: mobilecoin/full-service

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - namespace: test
            network: testnet
          - namespace: prod
            network: mainnet
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Generate Docker tags
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKERHUB_REPO }}
          flavor: |
            latest=false
            suffix=-${{ matrix.network }}
          tags: |
            type=semver,pattern=v{{version}},priority=20
            type=sha,priority=10

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Publish to DockerHub
        id: docker_publish_dockerhub
        uses: docker/build-push-action@v4
        with:
          build-args: |
            NAMESPACE=${{ matrix.namespace }}
          context: .
          file: .internal-ci/docker/Dockerfile.full-service-with-build
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
