name: rustdocs

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: [self-hosted, Linux, large]
    container:
      image: mobilecoin/rust-sgx-base:v0.0.22

    permissions:
      contents: write
      pages: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Restore core cache
        uses: actions/cache/restore@v3
        with:
          key: core
          path: |
            ~/.cargo
            ./target

      - name: Build documentation
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: target/doc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
